import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import escapeHtml from "npm:escape-html";
import { logger } from "../shared/logger.ts";

const RESEND_API_KEY = Deno.env.get('RESEND_API_KEY');

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

function buildEmailHeader(title: string): string {
  return `
    <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto; color: #333;">
      <h2 style="color: #2563eb;">New Market Alert: ${escapeHtml(title)}</h2>`;
}

function buildEmailMetadata(severity: string, minerals: string[]): string {
  const sevColor = severity === 'CRITICAL' ? '#dc2626' : '#d97706';
  const mineralsText = minerals.join(', ') || 'N/A';
  return `
      <div style="background-color: #f3f4f6; padding: 12px; border-radius: 8px; margin-bottom: 20px;">
        <p style="margin: 0;"><strong>Severity:</strong> <span style="color: ${sevColor}">${escapeHtml(severity)}</span></p>
        <p style="margin: 4px 0 0 0;"><strong>Minerals:</strong> ` + escapeHtml(mineralsText) + `</p>
      </div>`;
}

function buildEmailBody(description: string, rationale: string[]): string {
  const rationaleText = rationale.length > 0
    ? rationale.map(r => `• ${r}`).join('\n')
    : 'No specific rationale provided.';

  return `
      <p style="font-size: 16px; line-height: 1.5;">${escapeHtml(description)}</p>
      
      <div style="margin-top: 24px; border-top: 1px solid #e5e7eb; padding-top: 16px;">
        <h4 style="margin: 0 0 8px 0;">Rationale & Insights:</h4>
        <p style="margin: 0; color: #4b5563; white-space: pre-line; line-height: 1.6;">${escapeHtml(rationaleText)}</p>
      </div>`;
}

function buildEmailFooter(): string {
  return `
      <div style="margin-top: 32px; font-size: 12px; color: #9ca3af; text-align: center;">
        <p>This alert was automatically generated by CriMinerals AI Pipeline and reviewed by an Analyst.</p>
      </div>
    </div>`;
}

function buildEmailHtml(record: Record<string, unknown>): string {
  const title = typeof record.title === 'string' ? record.title : '';
  const severity = typeof record.severity === 'string' ? record.severity : 'MEDIUM';
  const description = typeof record.description === 'string' ? record.description : '';
  const minerals = Array.isArray(record.affected_minerals)
    ? record.affected_minerals.filter((m): m is string => typeof m === 'string')
    : [];
  const rationale = Array.isArray(record.rationale)
    ? record.rationale.filter((r): r is string => typeof r === 'string')
    : [];

  return buildEmailHeader(title) +
    buildEmailMetadata(severity, minerals) +
    buildEmailBody(description, rationale) +
    buildEmailFooter();
}

async function handleEmailRequest(req: Request): Promise<Response> {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders });
  }

  try {
    const payload = await req.json();
    const traceId = req.headers.get('trace_id') || 'unknown';
    
    // The webhook payload for UPDATE
    const record = payload.record as Record<string, unknown> | null | undefined;
    const oldRecord = payload.old_record as Record<string, unknown> | null | undefined;

    // Check if the record is transitioning to PUBLISHED
    // If oldRecord doesn't exist, it's an INSERT. If it does, we check if it changed.
    const isNowPublished = record?.status === 'PUBLISHED';
    const wasAlreadyPublished = oldRecord?.status === 'PUBLISHED';

    if (!record || !isNowPublished || wasAlreadyPublished) {
      return new Response("Not a newly published alert. Ignoring.", { status: 200, headers: corsHeaders });
    }

    if (!RESEND_API_KEY) {
      logger.warn("Missing RESEND_API_KEY", { traceId, alertId: record.id });
      // Don't fail the webhook completely if no key is set, just return
      return new Response("Email skipped: Missing RESEND_API_KEY", { status: 200, headers: corsHeaders });
    }

    const emailHtml = buildEmailHtml(record);

    const severityStr = typeof record.severity === 'string' ? record.severity : 'MEDIUM';
    const titleStr = typeof record.title === 'string' ? record.title : '';

    const res = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${RESEND_API_KEY}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        from: 'alerts@criminerals.com', // Best effort default
        to: ['analysts@criminerals.com'], // Best effort default
        subject: `[${severityStr}] ${titleStr}`,
        html: emailHtml,
      }),
    });

    if (!res.ok) {
      const errorText = await res.text();
      logger.error(`Resend API Error: ${errorText}`, new Error(errorText), { traceId, alertId: record.id });
      throw new Error(`Resend API Error: ${errorText}`);
    }

    logger.info("Email sent successfully", { traceId, alertId: record.id });

    return new Response(JSON.stringify({ success: true }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      status: 200,
    });

  } catch (error: unknown) {
    logger.error("Error sending market alert email", error, { traceId: req.headers.get('trace_id') });
    return new Response(JSON.stringify({ error: error instanceof Error ? error.message : 'Unknown error' }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      status: 500,
    });
  }
}

serve(async (req) => {
  try {
    return await handleEmailRequest(req);
  } finally {
    await logger.flush();
  }
});
