 
import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { logger } from "../shared/logger.ts";

const RESEND_API_KEY = Deno.env.get('RESEND_API_KEY');

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

function buildEmailHtml(record: Record<string, unknown>) {
  return `
    <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto; color: #333;">
      <h2 style="color: #2563eb;">New Market Alert: ${record.title}</h2>
      <div style="background-color: #f3f4f6; padding: 12px; border-radius: 8px; margin-bottom: 20px;">
        <p style="margin: 0;"><strong>Severity:</strong> <span style="color: ${record.severity === 'CRITICAL' ? '#dc2626' : '#d97706'}">${record.severity}</span></p>
        <p style="margin: 4px 0 0 0;"><strong>Minerals:</strong> ${Array.isArray(record.affected_minerals) ? record.affected_minerals.join(', ') : 'N/A'}</p>
      </div>
      
      <p style="font-size: 16px; line-height: 1.5;">${record.description}</p>
      
      <div style="margin-top: 24px; border-top: 1px solid #e5e7eb; padding-top: 16px;">
        <h4 style="margin: 0 0 8px 0;">Rationale & Insights:</h4>
        <ul style="margin: 0; padding-left: 20px; color: #4b5563;">
          ${Array.isArray(record.rationale) ? record.rationale.map((r: string) => `<li>${r}</li>`).join('') : '<li>No specific rationale provided.</li>'}
        </ul>
      </div>
      
      <div style="margin-top: 32px; font-size: 12px; color: #9ca3af; text-align: center;">
        <p>This alert was automatically generated by CriMinerals AI Pipeline and reviewed by an Analyst.</p>
      </div>
    </div>
  `;
}

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders });
  }

  try {
    const payload = await req.json();
    const traceId = req.headers.get('trace_id') || 'unknown';
    
    // The webhook payload for UPDATE
    const record = payload.record as Record<string, unknown>;
    const oldRecord = payload.old_record as Record<string, unknown>;

    // Check if the record is transitioning to PUBLISHED
    // If oldRecord doesn't exist, it's an INSERT. If it does, we check if it changed.
    const isNowPublished = record && record.status === 'PUBLISHED';
    const wasAlreadyPublished = oldRecord && oldRecord.status === 'PUBLISHED';

    if (!isNowPublished || wasAlreadyPublished) {
      return new Response("Not a newly published alert. Ignoring.", { status: 200, headers: corsHeaders });
    }

    if (!RESEND_API_KEY) {
      logger.warn("Missing RESEND_API_KEY", { traceId, alertId: record.id });
      // Don't fail the webhook completely if no key is set, just return
      return new Response("Email skipped: Missing RESEND_API_KEY", { status: 200, headers: corsHeaders });
    }

    const emailHtml = buildEmailHtml(record);

    const res = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${RESEND_API_KEY}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        from: 'alerts@criminerals.com', // Best effort default
        to: ['analysts@criminerals.com'], // Best effort default
        subject: `[${record.severity}] ${record.title}`,
        html: emailHtml,
      }),
    });

    if (!res.ok) {
      const errorText = await res.text();
      logger.error(`Resend API Error: ${errorText}`, new Error(errorText), { traceId, alertId: record.id });
      throw new Error(`Resend API Error: ${errorText}`);
    }

    logger.info("Email sent successfully", { traceId, alertId: record.id });

    return new Response(JSON.stringify({ success: true }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      status: 200,
    });

  } catch (error: unknown) {
    logger.error("Error sending market alert email", error, { traceId: req.headers.get('trace_id') });
    return new Response(JSON.stringify({ error: error instanceof Error ? error.message : 'Unknown error' }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      status: 500,
    });
  } finally {
    await logger.flush();
  }
});
